spring.application.name=SpringBootSecurityJPA

spring.jpa.hibernate.ddl-auto=update		
#or create
#spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/sales?createDatabaseIfNotExist=true&SSL=false
spring.datasource.username=root
spring.datasource.password=root@39

server.port=7799

logging.level.org.springframework.security=DEBUG
